module.exports = {
  // info messages
  USER_DELETED: 'USER_DELETED',

  // input validation
  NAME_REQUIRED: 'NAME_REQUIRED',
  EMAIL_INVALID: 'EMAIL_INVALID',
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  ROLE_REQUIRED: 'ROLE_REQUIRED',

  // db check
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_EXISTS: 'USER_NOT_EXISTS',

  // other errors
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  SERVER_ERROR: 'SERVER_ERROR'
};
