// alert
export const SET_ALERTS = 'SET_ALERTS';
export const REMOVE_ALERTS = 'REMOVE_ALERTS';

// titlebar
export const SET_TITLE = 'SET_LOADING';
export const REMOVE_TITLE = 'REMOVE_TITLE';

// auth
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERRORS = 'AUTH_ERRORS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';

// users
export const GET_USERS = 'GET_USERS';
export const CLEAR_USERS = 'CLEAR_USERS';
export const GET_USER = 'GET_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const FILTER_USERS = 'FILTER_USERS';
export const CLEAR_FILTER_USERS = 'CLEAR_FILTER_USERS';
export const USERS_ERRORS = 'USERS_ERRORS';
export const CLEAR_USERS_ERRORS = 'CLEAR_USERS_ERRORS';
export const SET_USERS_LOADING = 'SET_USERS_LOADING';

// artists
export const GET_ARTISTS = 'GET_ARTISTS';
export const CLEAR_ARTISTS = 'CLEAR_ARTISTS';
export const GET_ARTIST = 'GET_ARTIST';
export const CLEAR_ARTIST = 'CLEAR_ARTIST';
export const ADD_ARTIST = 'ADD_ARTIST';
export const UPDATE_ARTIST = 'UPDATE_ARTIST';
export const ARTISTS_ERRORS = 'ARTISTS_ERRORS';
export const CLEAR_ARTISTS_ERRORS = 'CLEAR_ARTISTS_ERRORS';
export const SET_ARTISTS_LOADING = 'SET_ARTISTS_LOADING';
export const GET_ART_DIRECTORS = 'GET_ART_DIRECTORS';
export const CLEAR_ART_DIRECTORS = 'CLEAR_ART_DIRECTORS';
export const SET_ART_DIRECTORS_LOADING = 'SET_ART_DIRECTORS_LOADING';
export const GET_EVENT_ARTISTS = 'GET_EVENT_ARTISTS';
export const CLEAR_EVENT_ARTISTS = 'CLEAR_EVENT_ARTISTS';
export const SET_EVENT_ARTISTS_LOADING = 'SET_EVENT_ARTISTS_LOADING';

// events
export const GET_EVENTS = 'GET_EVENTS';
export const CLEAR_EVENTS = 'CLEAR_EVENTS';
export const GET_EVENT = 'GET_EVENT';
export const CLEAR_EVENT = 'CLEAR_EVENT';
export const ADD_EVENT = 'ADD_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const EVENTS_ERRORS = 'EVENTS_ERRORS';
export const CLEAR_EVENTS_ERRORS = 'CLEAR_EVENTS_ERRORS';
export const SET_EVENTS_LOADING = 'SET_EVENTS_LOADING';

// phases
export const GET_PHASES = 'GET_PHASES';
export const CLEAR_PHASES = 'CLEAR_PHASES';
export const GET_PHASE = 'GET_PHASE';
export const CLEAR_PHASE = 'CLEAR_PHASE';
export const ADD_PHASE = 'ADD_PHASE';
export const UPDATE_PHASE = 'UPDATE_PHASE';
export const PHASES_ERRORS = 'PHASES_ERRORS';
export const CLEAR_PHASES_ERRORS = 'CLEAR_PHASES_ERRORS';
export const SET_PHASES_LOADING = 'SET_PHASES_LOADING';
export const GET_PHASE_EVENTS = 'GET_PHASE_EVENTS';
export const CLEAR_PHASE_EVENTS = 'CLEAR_PHASE_EVENTS';
export const SET_PHASE_EVENTS_LOADING = 'SET_PHASE_EVENTS_LOADING';
