export default {
  'Table.IndexColumnTitle': 'Idx',

  'Navbar.Title': '粵劇新秀演出系列',
  'Navbar.CloseNavbar': 'Close',
  'Navbar.Login': 'Login',
  'Navbar.Logout': 'Logout',
  'Navbar.Greeting': '你好',
  'Navbar.Users': 'Users',
  'Navbar.Artists': 'Artists',
  'Navbar.Events': 'Events',

  'Login.Title': 'Account Login',
  'Login.FillInAllFieldsMessage': 'Please fill in all fields',
  'Login.EmailLabel': 'Email',
  'Login.PasswordLabel': 'Password',
  'Login.LoginButton': 'Login',

  'User.NameLabel': 'Name',
  'User.EmailLabel': 'Email',
  'User.PasswordLabel': 'Password',
  'User.RoleLabel': 'Role',
  'User.CreateDTLabel': 'Create DT',
  'User.LastModifyDTLabel': 'Last Modify DT',
  'User.LastModifyUserLabel': 'Last Modify User',
  'User.IsEnabledLabel': 'Is Enabled ?',

  'Users.Title': 'Users',
  'Users.ForbiddenAccessMessage': 'You are forbidden to access user records.',

  'UserList.AddUserPrompt': 'Please add a user.',
  'UserList.AddUser': 'Add User',

  'UserEdit.BackToUserList': 'Back to User List',
  'UserEdit.AddUserTitle': 'Add User',
  'UserEdit.EditUserTitle': 'Edit User',
  'UserEdit.ConfirmPasswordLabel': 'Confirm Password',
  'UserEdit.AddUserSubmit': 'Add User',
  'UserEdit.UpdateUserSubmit': 'Update User',
  'UserEdit.AddUserSuccessMessage': 'User Added',
  'UserEdit.UpdateUserSuccessMessage': 'User Updated',
  'UserEdit.ConfirmPasswordDoesNotMatchMessage':
    'Confirm password does not match',

  'UserFilter.FilterTextPlaceHolder': 'Filter Users by name...',

  'Artists.Title': 'Artists',

  'Artist.NameTcLabel': 'Name TC',
  'Artist.NameScLabel': 'Name SC',
  'Artist.NameEnLabel': 'Name EN',
  'Artist.DescTcLabel': 'Desc TC',
  'Artist.DescScLabel': 'Desc SC',
  'Artist.DescEnLabel': 'Desc EN',
  'Artist.TypeLabel': 'Type',
  'Artist.RoleLabel': 'Role',
  'Artist.CreateDTLabel': 'Create DT',
  'Artist.LastModifyDTLabel': 'Last Modify DT',
  'Artist.LastModifyUserLabel': 'Last Modify User',
  'Artist.IsEnabledLabel': 'Is Enabled ?',

  'ArtistList.AddArtist': 'Add Artist',
  'ArtistList.FilterTextPlaceHolder': 'Filter Artists by name...',
  'ArtistList.FilterButton': 'Filter',
  'ArtistList.ClearFilterButton': 'Clear Filter',

  'ArtistEdit.BackToArtistList': 'Back to Artist List',
  'ArtistEdit.AddArtistTitle': 'Add Artist',
  'ArtistEdit.EditArtistTitle': 'Edit Artist',
  'ArtistEdit.AddArtistSubmit': 'Add Artist',
  'ArtistEdit.UpdateArtistSubmit': 'Update Artist',
  'ArtistEdit.AddArtistSuccessMessage': 'Artist Added',
  'ArtistEdit.UpdateArtistSuccessMessage': 'Artist Updated',

  'Events.Title': 'Events',

  'Event.NameTcLabel': 'Name TC',
  'Event.NameScLabel': 'Name SC',
  'Event.NameEnLabel': 'Name EN',
  'Event.DescTcLabel': 'Desc TC',
  'Event.DescScLabel': 'Desc SC',
  'Event.DescEnLabel': 'Desc EN',
  'Event.RemarksTcLabel': 'Remarks TC',
  'Event.RemarksScLabel': 'Remarks SC',
  'Event.RemarksEnLabel': 'Remarks EN',
  'Event.WriterTcLabel': 'Writer TC',
  'Event.WriterScLabel': 'Writer SC',
  'Event.WriterEnLabel': 'Writer EN',
  'Event.ArtDirectorsLabel': 'Art Directors',
  'Event.ArtistsLabel': 'Cast',
  'Event.ShowsLabel': 'Shows',
  'Event.CreateDTLabel': 'Create DT',
  'Event.LastModifyDTLabel': 'Last Modify DT',
  'Event.LastModifyUserLabel': 'Last Modify User',
  'Event.IsEnabledLabel': 'Is Enabled ?',

  'EventList.AddEvent': 'Add Event',
  'EventList.FilterTextPlaceHolder': 'Filter Events by name...',
  'EventList.FilterButton': 'Filter',
  'EventList.ClearFilterButton': 'Clear Filter',

  'EventEdit.BackToEventList': 'Back to Event List',
  'EventEdit.AddEventTitle': 'Add Event',
  'EventEdit.EditEventTitle': 'Edit Event',
  'EventEdit.AddEventSubmit': 'Add Event',
  'EventEdit.UpdateEventSubmit': 'Update Event',
  'EventEdit.AddEventSuccessMessage': 'Event Added',
  'EventEdit.UpdateEventSuccessMessage': 'Event Updated',

  'EventEdit.SelectArtDirectorsPlaceholder': 'Select Art Directors...',
  'EventEdit.Artist.RoleTcPlaceholder': 'Role TC',
  'EventEdit.Artist.RoleScPlaceholder': 'Role SC',
  'EventEdit.Artist.RoleEnPlaceholder': 'Role EN',
  'EventEdit.Artist.ArtistPlaceholder': 'Select Artist...',

  'Navbar.Testing': 'Testing Page'
};
