export default {
  'Table.IndexColumnTitle': 'Idx',

  'Navbar.Title': '粵劇新秀演出系列',
  'Navbar.Login': 'Login',
  'Navbar.Logout': 'Logout',
  'Navbar.Greeting': '你好',
  'Navbar.ChangePasswoed': 'Change Password',
  'Navbar.Users': 'Users',
  'Navbar.Artists': 'Artists',
  'Navbar.Events': 'Events',
  'Navbar.Phases': 'Phases',
  'Navbar.LandingPage': 'Landing Page',
  'Navbar.GlobalConstants': 'Global Constants',
  'Navbar.TicketingDefaultEdit': 'Ticketing Default',
  'Navbar.Testing': 'Testing Page',

  'Login.Title': 'Account Login',
  'Login.FillInAllFieldsMessage': 'Please fill in all fields',
  'Login.EmailLabel': 'Email',
  'Login.PasswordLabel': 'Password',
  'Login.LoginButton': 'Login',

  'User.NameLabel': 'Name',
  'User.EmailLabel': 'Email',
  'User.PasswordLabel': 'Password',
  'User.RoleLabel': 'Role',
  'User.CreateDTLabel': 'Create DT',
  'User.LastModifyDTLabel': 'Last Modify DT',
  'User.LastModifyUserLabel': 'Last Modify User',
  'User.IsEnabledLabel': 'Is Enabled ?',

  'Users.Title': 'Users',
  'Users.ForbiddenAccessMessage': 'You are forbidden to access user records.',

  'UserList.AddUserPrompt': 'Please add a user.',
  'UserList.AddUser': 'Add User',

  'UserEdit.BackToUserList': 'Back to User List',
  'UserEdit.AddUserTitle': 'Add User',
  'UserEdit.EditUserTitle': 'Edit User',
  'UserEdit.OldPasswordLabel': 'Old Password',
  'UserEdit.NewPasswordLabel': 'New Password',
  'UserEdit.ConfirmPasswordLabel': 'Confirm Password',
  'UserEdit.ChangePasswordLabel': 'Change Password',
  'UserEdit.CancelChangePasswordLabel': 'Cancel Change Password',
  'UserEdit.AddUserSubmit': 'Add User',
  'UserEdit.UpdateUserSubmit': 'Update User',
  'UserEdit.AddUserSuccessMessage': 'User Added',
  'UserEdit.UpdateUserSuccessMessage': 'User Updated',
  'UserEdit.ChangePasswordSuccessMessage': 'Password Updated',
  'UserEdit.ConfirmPasswordDoesNotMatchMessage':
    'Confirm password does not match',

  'UserFilter.FilterTextPlaceHolder': 'Filter Users by name...',

  'Artists.Title': 'Artists',

  'Artist.LabelLabel': 'Label',
  'Artist.NameTcLabel': 'Name TC',
  'Artist.NameScLabel': 'Name SC',
  'Artist.NameEnLabel': 'Name EN',
  'Artist.TypeLabel': 'Type',
  'Artist.RoleLabel': 'Role',
  'Artist.FeaturedImageLabel': 'Featured Image',
  'Artist.WithoutMaskImageLabel': 'Without Mask Image',
  'Artist.GalleryLabel': 'Gallery',
  'Artist.SoundLabel': 'Sound',
  'Artist.DescTcLabel': 'Desc TC',
  'Artist.DescScLabel': 'Desc SC',
  'Artist.DescEnLabel': 'Desc EN',
  'Artist.QnasLabel': 'Q & As',
  'Artist.CreateDTLabel': 'Create DT',
  'Artist.LastModifyDTLabel': 'Last Modify DT',
  'Artist.LastModifyUserLabel': 'Last Modify User',
  'Artist.IsEnabledLabel': 'Is Enabled ?',

  'ArtistList.AddArtist': 'Add Artist',
  'ArtistList.FilterTextPlaceHolder': 'Filter Artists by name...',
  'ArtistList.FilterButton': 'Filter',
  'ArtistList.ClearFilterButton': 'Clear Filter',

  'ArtistEdit.BackToArtistList': 'Back to Artist List',
  'ArtistEdit.AddArtistTitle': 'Add Artist',
  'ArtistEdit.EditArtistTitle': 'Edit Artist',
  'ArtistEdit.AddArtistSubmit': 'Add Artist',
  'ArtistEdit.UpdateArtistSubmit': 'Update Artist',
  'ArtistEdit.AddArtistSuccessMessage': 'Artist Added',
  'ArtistEdit.UpdateArtistSuccessMessage': 'Artist Updated',

  'ArtistEdit.Qna.QuestionTcPlaceholder': 'Question TC',
  'ArtistEdit.Qna.AnswerTcPlaceholder': 'Answer TC',
  'ArtistEdit.Qna.QuestionScPlaceholder': 'Question SC',
  'ArtistEdit.Qna.AnswerScPlaceholder': 'Answer SC',
  'ArtistEdit.Qna.QuestionEnPlaceholder': 'Question EN',
  'ArtistEdit.Qna.AnswerEnPlaceholder': 'Answer EN',

  'ArtistEdit.Media.Title': 'Media',

  'Events.Title': 'Events',

  'Event.LabelLabel': 'Label',
  'Event.NameTcLabel': 'Name TC',
  'Event.NameScLabel': 'Name SC',
  'Event.NameEnLabel': 'Name EN',
  'Event.ArtDirectorsLabel': 'Art Directors',
  'Event.ShowsLabel': 'Shows',
  'Event.ScenaristsLabel': 'Scenarists',
  'Event.DescHeadlineTcLabel': 'Desc Headline TC',
  'Event.DescHeadlineScLabel': 'Desc Headline SC',
  'Event.DescHeadlineEnLabel': 'Desc Headline EN',
  'Event.DescTcLabel': 'Desc TC',
  'Event.DescScLabel': 'Desc SC',
  'Event.DescEnLabel': 'Desc EN',
  'Event.RemarksTcLabel': 'Remarks TC',
  'Event.RemarksScLabel': 'Remarks SC',
  'Event.RemarksEnLabel': 'Remarks EN',
  'Event.FeaturedImageLabel': 'Featured Image',
  'Event.GalleryLabel': 'Gallery',
  'Event.ArtistsLabel': 'Cast',
  'Event.VenueTcLabel': 'Venue TC',
  'Event.VenueScLabel': 'Venue SC',
  'Event.VenueEnLabel': 'Venue EN',
  'Event.PricesLabel': 'Prices',
  'Event.PriceRemarksTcLabel': 'Price Remarks TC',
  'Event.PriceRemarksScLabel': 'Price Remarks SC',
  'Event.PriceRemarksEnLabel': 'Price Remarks EN',
  'Event.PhonesLabel': 'Phones',
  'Event.TicketUrlLabel': 'Ticket Url',
  'Event.ThemeColorLabel': 'Theme Color',
  'Event.CreateDTLabel': 'Create DT',
  'Event.LastModifyDTLabel': 'Last Modify DT',
  'Event.LastModifyUserLabel': 'Last Modify User',
  'Event.IsEnabledLabel': 'Is Enabled ?',

  'EventList.AddEvent': 'Add Event',
  'EventList.FilterTextPlaceHolder': 'Filter Events by name...',
  'EventList.FilterButton': 'Filter',
  'EventList.ClearFilterButton': 'Clear Filter',

  'EventEdit.BackToEventList': 'Back to Event List',
  'EventEdit.AddEventTitle': 'Add Event',
  'EventEdit.EditEventTitle': 'Edit Event',
  'EventEdit.AddEventSubmit': 'Add Event',
  'EventEdit.UpdateEventSubmit': 'Update Event',
  'EventEdit.AddEventSuccessMessage': 'Event Added',
  'EventEdit.UpdateEventSuccessMessage': 'Event Updated',

  'EventEdit.SelectArtDirectorsPlaceholder': 'Select Art Directors...',
  'EventEdit.Artist.RoleTcPlaceholder': 'Role TC',
  'EventEdit.Artist.RoleScPlaceholder': 'Role SC',
  'EventEdit.Artist.RoleEnPlaceholder': 'Role EN',
  'EventEdit.Artist.ArtistPlaceholder': 'Select Artist...',

  'EventEdit.Scenarist.NameTcPlaceholder': 'Name TC',
  'EventEdit.Scenarist.NameScPlaceholder': 'Name SC',
  'EventEdit.Scenarist.NameEnPlaceholder': 'Name EN',

  'EventEdit.Price.PriceTcPlaceholder': 'Price TC',
  'EventEdit.Price.PriceScPlaceholder': 'Price SC',
  'EventEdit.Price.PriceEnPlaceholder': 'Price EN',

  'EventEdit.Phone.LabelTcPlaceholder': 'Label TC',
  'EventEdit.Phone.LabelScPlaceholder': 'Label SC',
  'EventEdit.Phone.LabelEnPlaceholder': 'Label EN',
  'EventEdit.Phone.PhonePlaceholder': 'Phone',

  'EventEdit.Ticket.Title': 'Ticketing',

  'EventEdit.Media.Title': 'Media',

  'PhaseEdit.Show.SelectDatePlaceholder': 'Click to select date',

  'Phases.Title': 'Phases',
  'Phase.DerivedLabelLabel': 'Label',
  'Phase.YearLabel': 'Year',
  'Phase.PhaseNumberLabel': 'Phase Number',
  'Phase.ThemeColorLabel': 'Theme Color',
  'Phase.FromDateLabel': 'From Date',
  'Phase.ToDateLabel': 'To Date',
  'Phase.EventsLabel': 'Events',
  'Phase.CreateDTLabel': 'Create DT',
  'Phase.LastModifyDTLabel': 'Last Modify DT',
  'Phase.LastModifyUserLabel': 'Last Modify User',
  'Phase.IsEnabledLabel': 'Is Enabled ?',

  'PhaseList.AddPhase': 'Add Phase',
  'PhaseList.FilterTextPlaceHolder': 'Filter Phases by year...',
  'PhaseList.FilterButton': 'Filter',
  'PhaseList.ClearFilterButton': 'Clear Filter',

  'PhaseEdit.BackToPhaseList': 'Back to Phase List',
  'PhaseEdit.AddPhaseTitle': 'Add Phase',
  'PhaseEdit.EditPhaseTitle': 'Edit Phase',
  'PhaseEdit.AddPhaseSubmit': 'Add Phase',
  'PhaseEdit.UpdatePhaseSubmit': 'Update Phase',
  'PhaseEdit.AddPhaseSuccessMessage': 'Phase Added',
  'PhaseEdit.UpdatePhaseSuccessMessage': 'Phase Updated',

  'PhaseEdit.SelectEventsPlaceholder': 'Select Events...',
  'PhaseEdit.SelectFromDatePlaceholder': 'Click to select date',
  'PhaseEdit.SelectToDatePlaceholder': 'Click to select date',

  'LandingPage.Title': 'Landing Page',
  'LandingPage.FeaturedVideoLabel': 'Featured Video',
  'LandingPage.FeaturedVideo2Label': 'Featured Video 2',
  'LandingPage.FeaturedArtistsLabel': 'Featured Artists',
  'LandingPage.LastModifyDTLabel': 'Last Modify DT',
  'LandingPage.LastModifyUserLabel': 'Last Modify User',

  'LandingPageEdit.EditLandingPageTitle': 'Edit Landing Page',
  'LandingPageEdit.UpdateLandingPageSubmit': 'Update Landing Page',
  'LandingPageEdit.UpdateLandingPageSuccessMessage': 'Landing Page Updated',
  'LandingPageEdit.SelectFeaturedArtistsPlaceholder':
    'Select Featured Artists...',

  'GlobalConstants.Title': 'Global Constants',
  'GlobalConstants.LatestShowTcLabel': 'Latest Show TC',
  'GlobalConstants.LatestShowScLabel': 'Latest Show SC',
  'GlobalConstants.LatestShowEnLabel': 'Latest Show EN',
  'GlobalConstants.ScheduleOfShowTcLabel': 'Schedule Of Show TC',
  'GlobalConstants.ScheduleOfShowScLabel': 'Schedule Of Show SC',
  'GlobalConstants.ScheduleOfShowEnLabel': 'Schedule Of Show EN',
  'GlobalConstants.ArtDirectorTcLabel': 'Art Director TC',
  'GlobalConstants.ArtDirectorScLabel': 'Art Director SC',
  'GlobalConstants.ArtDirectorEnLabel': 'Art Director EN',
  'GlobalConstants.ActorTcLabel': 'Actor TC',
  'GlobalConstants.ActorScLabel': 'Actor SC',
  'GlobalConstants.ActorEnLabel': 'Actor EN',
  'GlobalConstants.DetailsOfShowTcLabel': 'Details Of Show TC',
  'GlobalConstants.DetailsOfShowScLabel': 'Details Of Show SC',
  'GlobalConstants.DetailsOfShowEnLabel': 'Details Of Show EN',
  'GlobalConstants.ShowTcLabel': 'Show TC',
  'GlobalConstants.ShowScLabel': 'Show SC',
  'GlobalConstants.ShowEnLabel': 'Show EN',
  'GlobalConstants.AllShowTcLabel': 'All Show TC',
  'GlobalConstants.AllShowScLabel': 'All Show SC',
  'GlobalConstants.AllShowEnLabel': 'All Show EN',
  'GlobalConstants.ActivitiesTcLabel': 'Activities TC',
  'GlobalConstants.ActivitiesScLabel': 'Activities SC',
  'GlobalConstants.ActivitiesEnLabel': 'Activities EN',
  'GlobalConstants.DownloadPDFTcLabel': 'Download PDF TC',
  'GlobalConstants.DownloadPDFScLabel': 'Download PDF SC',
  'GlobalConstants.DownloadPDFEnLabel': 'Download PDF EN',
  'GlobalConstants.OurActorsTcLabel': 'Our Actors TC',
  'GlobalConstants.OurActorsScLabel': 'Our Actors SC',
  'GlobalConstants.OurActorsEnLabel': 'Our Actors EN',
  'GlobalConstants.YmtTheaterTcLabel': 'YMT Theater TC',
  'GlobalConstants.YmtTheaterScLabel': 'YMT Theater SC',
  'GlobalConstants.YmtTheaterEnLabel': 'YMT Theater EN',
  'GlobalConstants.FollowUsTcLabel': 'Follow Us TC',
  'GlobalConstants.FollowUsScLabel': 'Follow Us SC',
  'GlobalConstants.FollowUsEnLabel': 'Follow Us EN',
  'GlobalConstants.AllTcLabel': 'All TC',
  'GlobalConstants.AllScLabel': 'All SC',
  'GlobalConstants.AllEnLabel': 'All EN',
  'GlobalConstants.BoyTcLabel': 'Boy TC',
  'GlobalConstants.BoyScLabel': 'Boy SC',
  'GlobalConstants.BoyEnLabel': 'Boy EN',
  'GlobalConstants.GirlTcLabel': 'Girl TC',
  'GlobalConstants.GirlScLabel': 'Girl SC',
  'GlobalConstants.GirlEnLabel': 'Girl EN',
  'GlobalConstants.InheritTcLabel': 'Inherit TC',
  'GlobalConstants.InheritScLabel': 'Inherit SC',
  'GlobalConstants.InheritEnLabel': 'Inherit EN',
  'GlobalConstants.ShareTcLabel': 'Share TC',
  'GlobalConstants.ShareScLabel': 'Share SC',
  'GlobalConstants.ShareEnLabel': 'Share EN',
  'GlobalConstants.RelatedShowTcLabel': 'Related Show TC',
  'GlobalConstants.RelatedShowScLabel': 'Related Show SC',
  'GlobalConstants.RelatedShowEnLabel': 'Related Show EN',
  'GlobalConstants.RelatedArtistsTcLabel': 'Related Artists TC',
  'GlobalConstants.RelatedArtistsScLabel': 'Related Artists SC',
  'GlobalConstants.RelatedArtistsEnLabel': 'Related Artists EN',
  'GlobalConstants.RelatedDramaTcLabel': 'Related Drama TC',
  'GlobalConstants.RelatedDramaScLabel': 'Related Drama SC',
  'GlobalConstants.RelatedDramaEnLabel': 'Related Drama EN',
  'GlobalConstants.AllShowsTcLabel': 'All Shows TC',
  'GlobalConstants.AllShowsScLabel': 'All Shows SC',
  'GlobalConstants.AllShowsEnLabel': 'All Shows EN',
  'GlobalConstants.MoreTcLabel': 'More TC',
  'GlobalConstants.MoreScLabel': 'More SC',
  'GlobalConstants.MoreEnLabel': 'More EN',
  'GlobalConstants.ScenaristTcLabel': 'Scenarist TC',
  'GlobalConstants.ScenaristScLabel': 'Scenarist SC',
  'GlobalConstants.ScenaristEnLabel': 'Scenarist EN',
  'GlobalConstants.IntroductionTcLabel': 'Introduction TC',
  'GlobalConstants.IntroductionScLabel': 'Introduction SC',
  'GlobalConstants.IntroductionEnLabel': 'Introduction EN',
  'GlobalConstants.BuyNowTcLabel': 'Buy Now TC',
  'GlobalConstants.BuyNowScLabel': 'Buy Now SC',
  'GlobalConstants.BuyNowEnLabel': 'Buy Now EN',
  'GlobalConstants.ParticipatingTcLabel': 'Participating TC',
  'GlobalConstants.ParticipatingScLabel': 'Participating SC',
  'GlobalConstants.ParticipatingEnLabel': 'Participating EN',
  'GlobalConstants.RoleTcLabel': 'Role TC',
  'GlobalConstants.RoleScLabel': 'Role SC',
  'GlobalConstants.RoleEnLabel': 'Role EN',
  'GlobalConstants.StudentShowTcLabel': 'Student Show TC',
  'GlobalConstants.StudentShowScLabel': 'Student Show SC',
  'GlobalConstants.StudentShowEnLabel': 'Student Show EN',
  'GlobalConstants.NextScheduleTcLabel': 'Next Schedule TC',
  'GlobalConstants.NextScheduleScLabel': 'Next Schedule SC',
  'GlobalConstants.NextScheduleEnLabel': 'Next Schedule EN',
  'GlobalConstants.LeaveContactTcLabel': 'Leave Contact TC',
  'GlobalConstants.LeaveContactScLabel': 'Leave Contact SC',
  'GlobalConstants.LeaveContactEnLabel': 'Leave Contact EN',
  'GlobalConstants.PublicShowTcLabel': 'Public Show TC',
  'GlobalConstants.PublicShowScLabel': 'Public Show SC',
  'GlobalConstants.PublicShowEnLabel': 'Public Show EN',
  'GlobalConstants.ProgramOfShowTcLabel': 'Program Of Show TC',
  'GlobalConstants.ProgramOfShowScLabel': 'Program Of Show SC',
  'GlobalConstants.ProgramOfShowEnLabel': 'Program Of Show EN',

  'GlobalConstants.LastModifyDTLabel': 'Last Modify DT',
  'GlobalConstants.LastModifyUserLabel': 'Last Modify User',

  'GlobalConstantsPageEdit.EditGlobalConstantsTitle': 'Edit Global Constants',
  'GlobalConstantsPageEdit.UpdateGlobalConstantsSubmit':
    'Update Global Constants',
  'GlobalConstantsPageEdit.UpdateGlobalConstantsSuccessMessage':
    'Global Constants Updated',

  'TicketingDefault.Title': 'Ticketing Default',
  'TicketingDefault.VenueTcLabel': 'Venue TC',
  'TicketingDefault.VenueScLabel': 'Venue SC',
  'TicketingDefault.VenueEnLabel': 'Venue EN',
  'TicketingDefault.PriceRemarksTcLabel': 'Price Remarks TC',
  'TicketingDefault.PriceRemarksScLabel': 'Price Remarks SC',
  'TicketingDefault.PriceRemarksEnLabel': 'Price Remarks EN',
  'TicketingDefault.ticketUrlLabel': 'Ticket Url',

  'TicketingDefault.LastModifyDTLabel': 'Last Modify DT',
  'TicketingDefault.LastModifyUserLabel': 'Last Modify User',

  'TicketingDefaultEdit.EditTicketingDefaultEditTitle':
    'Edit Ticketing Default',
  'TicketingDefaultEdit.EditSubmit': 'Update Ticketing Default',
  'TicketingDefaultEdit.UpdateTicketingDefaultEditSuccessMessage':
    'Ticketing Default Updated',

  'FileManager.SelectFile': 'Select File',
  'FileManager.DeleteFile': 'Delete File',
  'FileManager.UploadButton': 'Upload',
  'FileManager.DragToUploadHint': 'Drop File To Upload'
};
